### ISSUE TITLE
Panic on some png images

### ISSUE THREAD

**Issue by edwvee** [liut/jpegquality#2]
Yes, it's strange. But what if user named png image with jpeg extension, or there is just a broken data.
```
gopath\src\edwvee\jpegq>go run main.go
2018/06/03 23:37:00 length 3965
2018/06/03 23:37:00 Quantization table
2018/06/03 23:37:00   Precision=15; Table index=4 (chrominance)
2018/06/03 23:37:00 total 8576
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/liut/jpegquality.(*jpegReader).readQuality(0xc042002480, 0xc04200e0c8, 0x2, 0x2)
        gopath/src/github.com/liut/jpegquality/jpegquality.go:111 +0xcb0
github.com/liut/jpegquality.New(0x4e3940, 0xc042004028, 0x0, 0x0, 0x0)
        gopath/src/github.com/liut/jpegquality/jpegquality.go:44 +0x12f
main.main()
        gopath/src/edwvee/jpegq/main.go:17 +0xc2
exit status 2
```
Attached an example of code + image.
[jpegq.zip](https://github.com/liut/jpegquality/files/2066342/jpegq.zip)

**Comment by liut** [comment]
Sorry for tooooo late reply. I'll check it and PRs is welcome.
